[package]
name = "ray_tracer"
version = "0.1.0"
authors = ["Julien Dhénin"]
edition = "2021"

[dependencies]
glam = "0.24.2"
image = "0.24.7"
rand = "0.8.5"
rayon = "1.8"
tobj = "4.0"
yaml-rust = "0.4"